name: Tracker
version: 1.2.0
main: com.thebyteslayer.tracker.TrackerPlugin
api-version: 1.21
author: TheByteSlayer
description: A plugin to track players via compasses named after them.
website: https://github.com/thebyteslayer/projects/mctracker

 