name: Tracker
version: 1.0.1
main: com.thebyteslayer.tracker.TrackerPlugin
api-version: 1.21
author: TheByteSlayer
description: A plugin to track Players via compasses
website: https://github.com/thebyteslayer/tracker

 